CREATE DATABASE LIVRARIA;
USE LIVRARIA;
CREATE TABLE LIVROS (
NOMELIVRO VARCHAR (30),
NOMEAUTOR VARCHAR (30),
SEXOAUTOR CHAR (1),
NUMEROPAGINAS INT (11),
NOMEEDITORA VARCHAR (30),
VALORLIVRO FLOAT (10),
UFEDITORA VARCHAR (2),
ANOPUBLICACAO INT (5)
);

INSERT INTO LIVROS(NOMELIVRO,NOMEAUTOR,SEXOAUTOR,NUMEROPAGINAS,NOMEEDITORA,VALORLIVRO,UFEDITORA,ANOPUBLICACAO) VALUES('CAVALEIRO REAL','JOAO AUGUSTO','M',465,'ATLAS','150,25','PE',2000);
INSERT INTO LIVROS(NOMELIVRO,NOMEAUTOR,SEXOAUTOR,NUMEROPAGINAS,NOMEEDITORA,VALORLIVRO,UFEDITORA,ANOPUBLICACAO) VALUES('A ARTE DO FODA-SE','COPINE','M',123,'GLOBO','125','BA',2019);
INSERT INTO LIVROS(NOMELIVRO,NOMEAUTOR,SEXOAUTOR,NUMEROPAGINAS,NOMEEDITORA,VALORLIVRO,UFEDITORA,ANOPUBLICACAO) VALUES('MERCADO FINANCEIRO','FABIANA','F',965,'PORTUGA','99,90','RJ',2017);
INSERT INTO LIVROS(NOMELIVRO,NOMEAUTOR,SEXOAUTOR,NUMEROPAGINAS,NOMEEDITORA,VALORLIVRO,UFEDITORA,ANOPUBLICACAO) VALUES('GTA V','JOAQUINA','F',90,'ROCKSTAR','500,00','MG',2019);
INSERT INTO LIVROS(NOMELIVRO,NOMEAUTOR,SEXOAUTOR,NUMEROPAGINAS,NOMEEDITORA,VALORLIVRO,UFEDITORA,ANOPUBLICACAO) VALUES('PODER DA MENTE','MARIANA','F',53,'MARINHA','120,99','SP',1999);
INSERT INTO LIVROS(NOMELIVRO,NOMEAUTOR,SEXOAUTOR,NUMEROPAGINAS,NOMEEDITORA,VALORLIVRO,UFEDITORA,ANOPUBLICACAO) VALUES('CASA MARROM','CARLOS','M',235,'CUBO','23,90','SC',2005);
INSERT INTO LIVROS(NOMELIVRO,NOMEAUTOR,SEXOAUTOR,NUMEROPAGINAS,NOMEEDITORA,VALORLIVRO,UFEDITORA,ANOPUBLICACAO) VALUES('LA CASA PAPEL','NAIROBE','F',20,'CASA BRANCA','200','PE',2004);
INSERT INTO LIVROS(NOMELIVRO,NOMEAUTOR,SEXOAUTOR,NUMEROPAGINAS,NOMEEDITORA,VALORLIVRO,UFEDITORA,ANOPUBLICACAO) VALUES('CURSO CAKE','MARIA','F',20,'ARTGRAFFI','15,90','SP',2015);
INSERT INTO LIVROS(NOMELIVRO,NOMEAUTOR,SEXOAUTOR,NUMEROPAGINAS,NOMEEDITORA,VALORLIVRO,UFEDITORA,ANOPUBLICACAO) VALUES('A REALEZA','DORIA FERREIRA','M',35,'WORD','99,90','BA',1994);
INSERT INTO LIVROS(NOMELIVRO,NOMEAUTOR,SEXOAUTOR,NUMEROPAGINAS,NOMEEDITORA,VALORLIVRO,UFEDITORA,ANOPUBLICACAO) VALUES('COMO FAZER PAPAGAIO','ZÉ DA BARRACA','M',100,'ZEZIN','120,00','RJ',2001);

/*MOSTRAR TODOS OS BANCOS PROJETOS*/

SHOW TABLES;

/*USAR O BANCO DO PROJETO DESEJADO*/

USE NOME_DO_BANCO;

/*1 SELECIONAR TODA TABELA*/

SELECT * FROM LIVROS;

/*2 SELECIONAR NOME DO LIVRO E NOME DA EDITORA */

SELECT NOMELIVRO, NOMEEDITORA FROM LIVROS;

/*3 SELECIONAR NOME DO LIVRO E UF SEXO MASCULINO */

SELECT NOMELIVRO, UFEDITORA FROM LIVROS WHERE SEXOAUTOR = 'M';

/*4 SELECIONAR NOME DO LIVRO E NUMERO PAGINA SEXO FEMININO */

SELECT NOMELIVRO, NUMEROPAGINAS FROM LIVROS WHERE SEXOAUTOR = 'F';

/*5 SELECIONAR VALORES DOS LIVROS DE PE */

SELECT VALORLIVRO FROM LIVROS WHERE UFEDITORA = 'PE';

/* SELECIONAR AUTORES SEXO MASCULINO QUE TIVERAM LIVROS PUBLICADOS EM SP OU RJ*/

SELECT NOMEAUTOR, SEXOAUTOR FROM LIVROS WHERE SEXOAUTOR = 'M' AND UFEDITORA = 'SP' OR UFEDITORA = 'RJ';



